# Ejercicio 1: Tensores
Crea los siguientes tensores utilizando PyTorch haciendo explícito el tipo de dato que contiene cada
tensor:

In [1]:
import torch

1. $x^T = (1 \;\;\; 3 \;\;\; 7 \;\;\; 8 \;\;\; 11 \;\;\; 345 \;\;\; 1)$

In [11]:
x1 = torch.tensor([1, 3, 7, 8, 11, 345, 1], dtype=torch.int32)
print(x1)
print('Tipo de dato: ', x1.dtype)

tensor([  1,   3,   7,   8,  11, 345,   1], dtype=torch.int32)
Tipo de dato:  torch.int32


2. $x^T = (0.5 \;\;\; 0.7 \;\;\; 2 \;\;\; 0.66 \;\;\; 10 \;\;\; 345 \;\;\; 0.01)$

In [15]:
x2 = torch.FloatTensor([0.5, 0.7, 2, 0.66, 10, 345, 0.01])
print(x2)
print('Tipo de dato: ', x2.dtype)

tensor([5.0000e-01, 7.0000e-01, 2.0000e+00, 6.6000e-01, 1.0000e+01, 3.4500e+02,
        1.0000e-02])
Tipo de dato:  torch.float32


3. $A =
\begin{pmatrix}
10 & 0 & 15 \\
2 & 9 & 12 \\
\end{pmatrix}
$

In [6]:
A = torch.IntTensor([[10, 0, 15],
                     [2, 9, 12]])
print(A)
print('Tipo de dato: ', A.dtype)

tensor([[10,  0, 15],
        [ 2,  9, 12]], dtype=torch.int32)
Tipo de dato:  torch.int32


4. $B =
\begin{pmatrix}
1 & 3 & 7 & 8 & 11 & 345 & 1\\
0.5 & 0.7 & 2 & 0.66 & 10 & 345 & 0.01 \\
\end{pmatrix}
$

In [8]:
B = torch.FloatTensor([[1, 3, 7, 8, 11, 345, 1],
                       [0.5, 0.7, 2, 0.66, 10, 345, 0.01]])
print(B)
print('Tipo de dato: ', B.dtype)

tensor([[1.0000e+00, 3.0000e+00, 7.0000e+00, 8.0000e+00, 1.1000e+01, 3.4500e+02,
         1.0000e+00],
        [5.0000e-01, 7.0000e-01, 2.0000e+00, 6.6000e-01, 1.0000e+01, 3.4500e+02,
         1.0000e-02]])
Tipo de dato:  torch.float32


5. $T = [[[1, 7], [ 4, 10]], [[ 2, 8], [ 5, 11]], [[ 3, 9], [ 6, 12]]]$

In [13]:
T = torch.IntTensor([[[ 1, 7], 
                      [ 4, 10]],
                     
                     [[ 2, 8], 
                      [ 5, 11]],

                     [[ 3, 9], 
                      [ 6, 12]]])
print(T)
print('Tipo de dato: ', T.dtype)

tensor([[[ 1,  7],
         [ 4, 10]],

        [[ 2,  8],
         [ 5, 11]],

        [[ 3,  9],
         [ 6, 12]]], dtype=torch.int32)
Tipo de dato:  torch.int32


6. $𝑆 = [[[4, 9], [4, 4]], [[8, 0], [1, 7]], [[2, 6], [5, 6]]]$

In [10]:
S = torch.IntTensor([[[4, 9], 
                      [4, 4]],
                     
                     [[8, 0], 
                      [1, 7]],

                     [[2, 6], 
                      [5, 6]]])
print(S)
print('Tipo de dato: ', S.dtype)

tensor([[[4, 9],
         [4, 4]],

        [[8, 0],
         [1, 7]],

        [[2, 6],
         [5, 6]]], dtype=torch.int32)
Tipo de dato:  torch.int32


Y a partir de estos realiza las siguientes operaciones:

1. Obtener el tamaño de cada tensor.

In [20]:
tensores = [x1, x2, A, B, T, S]
for ts in tensores:
    print('{} \ntiene dimensiones: {}\n\n'.format(ts, ts.size()))

tensor([  1,   3,   7,   8,  11, 345,   1], dtype=torch.int32) 
tiene dimensiones: torch.Size([7])


tensor([5.0000e-01, 7.0000e-01, 2.0000e+00, 6.6000e-01, 1.0000e+01, 3.4500e+02,
        1.0000e-02]) 
tiene dimensiones: torch.Size([7])


tensor([[10,  0, 15],
        [ 2,  9, 12]], dtype=torch.int32) 
tiene dimensiones: torch.Size([2, 3])


tensor([[1.0000e+00, 3.0000e+00, 7.0000e+00, 8.0000e+00, 1.1000e+01, 3.4500e+02,
         1.0000e+00],
        [5.0000e-01, 7.0000e-01, 2.0000e+00, 6.6000e-01, 1.0000e+01, 3.4500e+02,
         1.0000e-02]]) 
tiene dimensiones: torch.Size([2, 7])


tensor([[[ 1,  7],
         [ 4, 10]],

        [[ 2,  8],
         [ 5, 11]],

        [[ 3,  9],
         [ 6, 12]]], dtype=torch.int32) 
tiene dimensiones: torch.Size([3, 2, 2])


tensor([[[4, 9],
         [4, 4]],

        [[8, 0],
         [1, 7]],

        [[2, 6],
         [5, 6]]], dtype=torch.int32) 
tiene dimensiones: torch.Size([3, 2, 2])




2. Obtener las sumas x + y (x1 + x2?), T + S

In [23]:
print('(x + y)^T =\n', x1 + x2)
print('T + S =\n', T + S)

(x + y)^T =
 tensor([  1.5000,   3.7000,   9.0000,   8.6600,  21.0000, 690.0000,   1.0100])
T + S =
 tensor([[[ 5, 16],
         [ 8, 14]],

        [[10,  8],
         [ 6, 18]],

        [[ 5, 15],
         [11, 18]]], dtype=torch.int32)


3. Obtener el producto externo entre x e y.

In [25]:
had = x1 * x2
print('{}\n  o  \n{}\n = \n{}'.format(x1, x2, had))

tensor([  1,   3,   7,   8,  11, 345,   1], dtype=torch.int32)
  o  
tensor([5.0000e-01, 7.0000e-01, 2.0000e+00, 6.6000e-01, 1.0000e+01, 3.4500e+02,
        1.0000e-02])
 = 
tensor([5.0000e-01, 2.1000e+00, 1.4000e+01, 5.2800e+00, 1.1000e+02, 1.1902e+05,
        1.0000e-02])


4. Obtener el producto de Haddamard entre T y S.

In [26]:
had = T * S
print('{}\n  o  \n{}\n = \n{}'.format(T, S, had))

tensor([[[ 1,  7],
         [ 4, 10]],

        [[ 2,  8],
         [ 5, 11]],

        [[ 3,  9],
         [ 6, 12]]], dtype=torch.int32)
  o  
tensor([[[4, 9],
         [4, 4]],

        [[8, 0],
         [1, 7]],

        [[2, 6],
         [5, 6]]], dtype=torch.int32)
 = 
tensor([[[ 4, 63],
         [16, 40]],

        [[16,  0],
         [ 5, 77]],

        [[ 6, 54],
         [30, 72]]], dtype=torch.int32)


5. Obtener los productos Bx y By.

In [38]:
# Transformar al mismo tipo de dato float
x1 = x1.type(torch.FloatTensor)

Bx = torch.matmul(B,x1.T)
print('{}\n  •  \n{}\n = \n{}'.format(B,x1, Bx))

tensor([[1.0000e+00, 3.0000e+00, 7.0000e+00, 8.0000e+00, 1.1000e+01, 3.4500e+02,
         1.0000e+00],
        [5.0000e-01, 7.0000e-01, 2.0000e+00, 6.6000e-01, 1.0000e+01, 3.4500e+02,
         1.0000e-02]])
  •  
tensor([  1.,   3.,   7.,   8.,  11., 345.,   1.])
 = 
tensor([119270.0000, 119156.8906])


In [39]:
By = torch.matmul(B,x2.T)
print('{}\n  •  \n{}\n = \n{}'.format(B,x2, By))

tensor([[1.0000e+00, 3.0000e+00, 7.0000e+00, 8.0000e+00, 1.1000e+01, 3.4500e+02,
         1.0000e+00],
        [5.0000e-01, 7.0000e-01, 2.0000e+00, 6.6000e-01, 1.0000e+01, 3.4500e+02,
         1.0000e-02]])
  •  
tensor([5.0000e-01, 7.0000e-01, 2.0000e+00, 6.6000e-01, 1.0000e+01, 3.4500e+02,
        1.0000e-02])
 = 
tensor([119156.8906, 119130.1719])


6. Existen dos forma de obtener un producto entre A y B usando transposición, encuentra estas
formas y haz una multiplicación con ambas matrices

In [44]:
# Transformar al mismo tipo de dato float
A = A.type(torch.FloatTensor)

# Recorar tamaño de ambos vectores:
print("Tamaño de A: ", A.size())
print("Tamaño de B: ", B.size())

Tamaño de A:  torch.Size([2, 3])
Tamaño de B:  torch.Size([2, 7])


In [45]:
# La multiplicación entre matrices está definida para
# matrices de dimension mxd por matrices de dxn
# Por ello, hay que llevar los tensores a esta forma usando transposición.

print("Forma 1 (A transpuesta): ")
AtB = torch.matmul(A.T, B)
print('{}\n  •  \n{}\n = \n{}'.format(A.T, B, AtB))

Forma 1 (A transpuesta): 
tensor([[10.,  2.],
        [ 0.,  9.],
        [15., 12.]])
  •  
tensor([[1.0000e+00, 3.0000e+00, 7.0000e+00, 8.0000e+00, 1.1000e+01, 3.4500e+02,
         1.0000e+00],
        [5.0000e-01, 7.0000e-01, 2.0000e+00, 6.6000e-01, 1.0000e+01, 3.4500e+02,
         1.0000e-02]])
 = 
tensor([[1.1000e+01, 3.1400e+01, 7.4000e+01, 8.1320e+01, 1.3000e+02, 4.1400e+03,
         1.0020e+01],
        [4.5000e+00, 6.3000e+00, 1.8000e+01, 5.9400e+00, 9.0000e+01, 3.1050e+03,
         9.0000e-02],
        [2.1000e+01, 5.3400e+01, 1.2900e+02, 1.2792e+02, 2.8500e+02, 9.3150e+03,
         1.5120e+01]])


In [47]:
print("Forma 2 (B transpuesta): ")
BtA = torch.matmul(B.T, A)
print('{}\n  •  \n{}\n = \n{}'.format(B.T, A, BtA))

Forma 2 (B transpuesta): 
tensor([[1.0000e+00, 5.0000e-01],
        [3.0000e+00, 7.0000e-01],
        [7.0000e+00, 2.0000e+00],
        [8.0000e+00, 6.6000e-01],
        [1.1000e+01, 1.0000e+01],
        [3.4500e+02, 3.4500e+02],
        [1.0000e+00, 1.0000e-02]])
  •  
tensor([[10.,  0., 15.],
        [ 2.,  9., 12.]])
 = 
tensor([[1.1000e+01, 4.5000e+00, 2.1000e+01],
        [3.1400e+01, 6.3000e+00, 5.3400e+01],
        [7.4000e+01, 1.8000e+01, 1.2900e+02],
        [8.1320e+01, 5.9400e+00, 1.2792e+02],
        [1.3000e+02, 9.0000e+01, 2.8500e+02],
        [4.1400e+03, 3.1050e+03, 9.3150e+03],
        [1.0020e+01, 9.0000e-02, 1.5120e+01]])


# Ejercicio 2: Gráficas y manejo de tensores con PyTorch
Utilizando tensores en PyTorch con requerimiento de gradiente, realiza las gráficas computacionales
en PyTorch de las siguientes funciones sig

1. Define la función $$f_1 (x) = \text{exp}\{  2x_1 + 2x_2 + 3x_3 + 0.5\}$$

utilizando 3 nodos (requiere tres variables).

In [95]:
def f1(x): 
    # Define el paso forward
    node_one = torch.matmul(x, torch.tensor([2.,2.,3.]))
    node_two = node_one + 0.5
    node_three = torch.exp(node_two) 
    
    return node_three

    
# Generar vector
x = torch.tensor([1., 3., 4.], requires_grad=True)
# Computa forward
output = f1(x)
# Computa el backward y gradiente
output.backward()
print(x.grad)

tensor([1.5998e+09, 1.5998e+09, 2.3997e+09])


2. Define la función $$f_2 (x) = (  x_1^2 - 2x_2^2 + 4x_3^2 )^2$$

utilizando 3 nodos (requiere tres variables).

In [96]:
def f2(x): 
    # Define el paso forward
    node_one = x ** 2
    node_two = torch.matmul(node_one, torch.tensor([1., -2., 4.]))
    node_three = node_two ** 2
    
    return node_three

    
# Generar vector
x = torch.tensor([1., 3., 4.], requires_grad=True)
# Computa forward
output = f2(x)
# Computa el backward y gradiente
output.backward()
print(x.grad)

tensor([  188., -1128.,  3008.])


3. Define la función $$f_3 (x) = \frac{\cos^2(x_1^2) + \cos^2 (x_2^2) + \cos^2 (x_3^2)}{||x||}$$

utilizando 5 nodos (requiere tres variables).

In [104]:
def f3(x): 
    # Define el paso forward
    node_one = x ** 2
    node_two = torch.cos(node_one)
    node_three = node_two ** 2
    node_four = torch.linalg.norm(x)
    node_five = torch.sum(node_three) / node_four
    
    return node_five

    
# Generar vector
x = torch.tensor([1., 3., 4.], requires_grad=True)
# Computa forward
output = f3(x)
# Computa el backward y gradiente
output.backward()
print(x.grad)

tensor([-0.3720,  0.8375, -0.9267])


# Ejercicio 3: Gráfica computacionales
Define los nodos de una gráfica computacional para una red neuronal generando los nodos como
clases de python y utilizando únicamente numpy (no usar PyTorch, ni paqueterías especiales).
Genera los nodos para las funciones siguientes:

In [106]:
import random
import numpy as np

In [157]:
class Node:
    # Nodo de entrada | ya que x es un vector según las indicaciones
    # No es necesario considerar valores numéricos
    def __init__(self, value):
        self.grad = None
        self.value = np.array(value)

    def __str__(self):
        return str(self.value)

1. Linear: $\omega x + b$ donde $\omega$ y $b$ se inician de forma aleatoria. Debe tomar como argumentos el
tamaño de entrada del vector y el de salida.

In [163]:
class Linear():
    def __init__(self, input_size, output_size):
        self.grad = None
        #Inicializa w y b
        self.w = np.random.random((output_size, input_size))
        self.b = np.random.random(output_size)

    def __call__(self, x):
        # Convertir x a nodo
        if not isinstance(x, Node):
            x = Node(x)

        # Realiza la función de wx+b
        self.value = np.dot(self.w, x.value) + self.b
        self.parent = x
        return self

    def __str__(self):
        return str(self.value)

2. Tanh: Función de activación de tangente hiperbólica definida como $\tanh(x) = \frac{e^x - e^{-x}}{e^x + e^{-x}}$.

In [166]:
class Tanh():
    def __init__(self):
        self.grad = None

    def __call__(self, x):
        # Convertir x a nodo
        if not isinstance(x, Node):
            x = Node(x)
        # Realiza la función de tanh
        print(type(x.value))
        self.value = (np.exp(x.value) - np.exp(-x.value)) / (np.exp(x.value) + np.exp(-x.value))
        self.parent = x
        return self

    def __str__(self):
        return str(self.value)

3. Softmax: Función de activación definida como $\text{softmax} (x_i) = \frac{e_i^x}{\sum_j e^{x_j}}$ donde cada $x_i$ es una entrada del vector.

In [160]:
class Softmax():
    def __init__(self):
        self.grad = None

    def __call__(self, x):
        # Convertir x a nodo
        if not isinstance(x, Node):
            x = Node(x)
            
        # Realiza la función de Softmax
        self.value = np.exp(x.value) / np.sum(x.value)
        self.parent = x
        return self

    def __str__(self):
        return str(self.value)

4. CrossEntropy: Función que toma dos argumentos $x$ (vector) y $y$ (un entero o clase) y que se
estima de la forma $$R(x) = - \sum_j \delta_{j,y} \ln x_j$$ donde $\delta_{j,y} = 1$ si $j=y$ y $0$ en otro caso.

In [161]:
class CrossEntropy():
    def __init__(self):
        self.grad = None

    def __call__(self, x, y):
        # Convertir x a nodo
        if not isinstance(x, Node):
            x = Node(x)
             
        # Se asegura que los valores están dentro del rango de logaritmo
        epsilon = 1e-15
        x_clip = np.clip(x.value, epsilon)

        # Ajusta el tipo de dato a array
        if isinstance(y, (list, np.ndarray)):
            # Asumimos que se refiere a clase como un conjunto de indices agrupados
            y = np.array(y)
        elif isinstance(y, int):
            y = np.array([y])

        # Realiza la función de R
        self.value = - np.sum( np.log(x_clip[y]) )
        self.parentA = x
        self.parentB = y
        return self

    def __str__(self):
        return str(self.value)

In [ ]:
l1 = Linear(2,3)
act1 = Tanh()
l2 = Linear(3,2)
out = Softmax()
criterion = CrossEntropy()
x = np.array([1,2])
pred = out(l2(act1(l1(x))))
loss = criterion(pred, 1)
print(pred)
print(loss)